version: '3.7'

services:

  database-checkout:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: testdb
    container_name: db-testdb
    ports:
      - 5432:5432